// src/auth/permissions.ts
import { createAccessControl } from "better-auth/plugins/access";
import {
	adminAc,
	defaultStatements,
	ownerAc,
} from "better-auth/plugins/organization/access";

export const statements = {
	...defaultStatements,
	product: ["create", "update", "delete", "read"],
	stock: ["adjust", "read"],
	supplier: ["create", "update", "delete", "read"],
	order: [
		"create",
		"update",
		"delete",
		"read",
		"approve",
		"ship",
		"cancel",
		"complete",
	],
	review: ["moderate", "delete", "read"],
	location: ["create", "update", "delete", "read"],
	organization: ["create", "update", "delete", "read"],
	report: ["read", "export"],
	brand: ["create", "read", "update", "delete"],
	shipping: ["create", "read", "update", "delete"],
	rewards: ["read", "write", "delete"],
	inventory: ["read", "create"],
	productVariant: ["create", "read", "update", "delete"],
	productCollection: ["create", "read", "update", "delete"],
	productReview: ["create", "read", "update", "delete"],
	client: ["create", "read", "update", "delete", "admin"],
	organization_info: ["delete"],
	expense: ["create", "read", "update", "delete", "approve", "reject", "pay"],
	expense_category: ["create", "read", "update", "delete"],
	payout: ["read", "approve", "reject", "mark_paid"],
	invoice: ["create", "read", "update", "delete", "approve", "void"],
	payment: ["create", "read", "update", "delete"],
	account: ["create", "read", "update", "delete"],
	journal: ["create", "read", "post", "delete"],
	employee: ["create", "read", "update", "delete"],
	payroll: [
		"create",
		"read",
		"update",
		"delete",
		"calculate",
		"approve",
		"process_payment",
	],
	salary_advance: ["request", "read", "approve", "disburse"],
	salary_component: ["create", "read", "update", "delete"],
	salary_structure: ["create", "read", "update", "delete"],
} as const;

export type Resource = keyof typeof statements;

export const ac = createAccessControl(statements);

/**
 * Roles (merge your custom perms with built-ins if you want to keep them)
 */
export const roles = {
	owner: ac.newRole({
		...ownerAc.statements,
		product: ["create", "update", "delete", "read"],
		stock: ["adjust", "read"],
		supplier: ["create", "update", "delete", "read"],
		order: [
			"create",
			"update",
			"delete",
			"read",
			"approve",
			"ship",
			"cancel",
			"complete",
		],
		review: ["moderate", "delete", "read"],
		location: ["create", "update", "delete", "read"],
		organization: ["create", "update", "delete", "read"],
		report: ["read", "export"],
		brand: ["create", "read", "update", "delete"],
		shipping: ["create", "read", "update", "delete"],
		rewards: ["read", "write", "delete"],
		inventory: ["read", "create"],
		productVariant: ["create", "read", "update", "delete"],
		productCollection: ["create", "read", "update", "delete"],
		productReview: ["create", "read", "update", "delete"],
		client: ["create", "read", "update", "delete", "admin"],
		organization_info: ["delete"],
		expense: ["create", "read", "update", "delete", "approve", "reject", "pay"],
		expense_category: ["create", "read", "update", "delete"],
		payout: ["read", "approve", "reject", "mark_paid"],
		invoice: ["create", "read", "update", "delete", "approve", "void"],
		payment: ["create", "read", "update", "delete"],
		account: ["create", "read", "update", "delete"],
		journal: ["create", "read", "post", "delete"],
		employee: ["create", "read", "update", "delete"],
		payroll: [
			"create",
			"read",
			"update",
			"delete",
			"calculate",
			"approve",
			"process_payment",
		],
		salary_advance: ["request", "read", "approve", "disburse"],
		salary_component: ["create", "read", "update", "delete"],
		salary_structure: ["create", "read", "update", "delete"],
	}),
	admin: ac.newRole({
		...adminAc.statements,
		product: ["create", "update", "read"],
		stock: ["adjust", "read"],
		supplier: ["create", "update", "read"],
		order: ["create", "update", "read", "approve", "ship", "complete"],
		review: ["moderate", "read"],
		location: ["create", "update", "read"],
		organization: ["update", "read"],
		report: ["read", "export"],
		brand: ["create", "read", "update"],
		shipping: ["create", "read", "update"],
		rewards: ["read", "write"],
		inventory: ["read", "create"],
		productVariant: ["create", "read", "update"],
		productCollection: ["create", "read", "update"],
		productReview: ["create", "read", "update"],
		client: ["create", "read", "update", "admin"],
		expense: ["create", "read", "update", "approve", "reject", "pay"],
		expense_category: ["create", "read", "update"],
		payout: ["read", "approve", "reject", "mark_paid"],
		invoice: ["create", "read", "update", "approve", "void"],
		payment: ["create", "read", "update"],
		account: ["create", "read", "update"],
		journal: ["create", "read", "post"],
		employee: ["create", "read", "update"],
		payroll: [
			"create",
			"read",
			"update",
			"calculate",
			"approve",
			"process_payment",
		],
		salary_advance: ["request", "read", "approve", "disburse"],
		salary_component: ["create", "read", "update"],
		salary_structure: ["create", "read", "update"],
	}),
	manager: ac.newRole({
		product: ["update", "read"],
		stock: ["adjust", "read"],
		supplier: ["read"],
		order: ["create", "update", "read", "ship"],
		review: ["read"],
		location: ["read"],
		report: ["read"],
	}),
	staff: ac.newRole({
		product: ["read"],
		stock: ["read"],
		order: ["create", "update", "read"],
		review: ["read"],
		location: ["read"],
	}),
} as const;
